// Generated by scripts/generate-ipc-methods.ts. DO NOT EDIT.

import type { CredentialItem, TicketQueueOption, TicketResponse, TicketResult, TicketType } from '../orm_types'

export interface IpcInvokeMap {
  'add-ticket-option': {
    params: [item: TicketQueueOption]
    return: Promise<void>
  }
  'clear-ticket-history': {
    params: []
    return: Promise<void>
  }
  'clearCredential': {
    params: []
    return: Promise<void>
  }
  'delete-ticket-option': {
    params: [queue: string]
    return: Promise<void>
  }
  'get-domain-user': {
    params: []
    return: Promise<string>
  }
  'get-ticket-history': {
    params: []
    return: Promise<TicketResult[]>
  }
  'get-ticket-options': {
    params: []
    return: Promise<TicketQueueOption[]>
  }
  'getCurrent': {
    params: []
    return: Promise<CredentialItem>
  }
  'msg': {
    params: [msg: string]
    return: Observable<string>
  }
  'open-link': {
    params: [url: string]
    return: Promise<void>
  }
  'readCredential': {
    params: []
    return: Promise<CredentialItem[]>
  }
  'reset-ticket-options': {
    params: []
    return: Promise<TicketQueueOption[]>
  }
  'save-ticket-history': {
    params: [item: TicketResult]
    return: Promise<void>
  }
  'saveCredential': {
    params: [data: CredentialItem[]]
    return: Promise<true>
  }
  'ticket': {
    params: [data: TicketType]
    return: Promise<TicketResponse>
  }
}

export type IpcChannel = keyof IpcInvokeMap

export type IpcInvokeArgs<T extends IpcChannel> = IpcInvokeMap[T]['params']
export type IpcInvokeReturn<T extends IpcChannel> = IpcInvokeMap[T]['return'] extends Promise<unknown>
  ? IpcInvokeMap[T]['return']
  : Promise<IpcInvokeMap[T]['return']>

export {}
