// Generated by scripts/generate-ipc-methods.ts. DO NOT EDIT.

import type { CredentialItem, TicketHistoryItem, TicketQueueOption, TicketResponse, TicketType } from '../orm_types'

export interface IpcInvokeMap {
  'add-ticket-option': {
    params: [item: TicketQueueOption]
    return: Promise<void>
  }
  'check-for-app-updates': {
    params: []
    return: Promise<ManualUpdateResult>
  }
  'clear-ticket-history': {
    params: []
    return: Promise<void>
  }
  'clearCredential': {
    params: []
    return: Promise<void>
  }
  'delete-ticket-option': {
    params: [queue: string]
    return: Promise<void>
  }
  'download-app-update': {
    params: []
    return: Promise<ManualUpdateResult>
  }
  'get-app-version': {
    params: []
    return: Promise<string>
  }
  'get-domain-user': {
    params: []
    return: Promise<string>
  }
  'get-ticket-history': {
    params: []
    return: Promise<TicketHistoryItem[]>
  }
  'get-ticket-options': {
    params: []
    return: Promise<TicketQueueOption[]>
  }
  'get-update-preferences': {
    params: []
    return: Promise<UpdatePreferences>
  }
  'getCurrent': {
    params: []
    return: Promise<CredentialItem>
  }
  'install-downloaded-app-update': {
    params: []
    return: Promise<boolean>
  }
  'internal-ticket': {
    params: [data: TicketType]
    return: Promise<TicketResponse>
  }
  'is-domain-environment': {
    params: []
    return: Promise<boolean>
  }
  'open-link': {
    params: [url: string]
    return: Promise<void>
  }
  'readCredential': {
    params: []
    return: Promise<CredentialItem[]>
  }
  'reset-ticket-options': {
    params: []
    return: Promise<TicketQueueOption[]>
  }
  'save-ticket-history': {
    params: [item: TicketHistoryItem]
    return: Promise<void>
  }
  'saveCredential': {
    params: [data: CredentialItem[]]
    return: Promise<true>
  }
  'set-update-preferences': {
    params: [partialPreferences: { includeBeta?: boolean | undefined; } | undefined]
    return: Promise<UpdatePreferences>
  }
  'sync-ticket-options-from-github': {
    params: [mode: "merge" | "overwrite"]
    return: Promise<TicketQueueOption[]>
  }
  'ticket': {
    params: [data: TicketType]
    return: Promise<TicketResponse>
  }
}

export type IpcChannel = keyof IpcInvokeMap

export type IpcInvokeArgs<T extends IpcChannel> = IpcInvokeMap[T]['params']
export type IpcInvokeReturn<T extends IpcChannel> = IpcInvokeMap[T]['return'] extends Promise<unknown>
  ? IpcInvokeMap[T]['return']
  : Promise<IpcInvokeMap[T]['return']>

export {}
