/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/help/help': RouteRecordInfo<
      '/help/help',
      '/help/help',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/credentials': RouteRecordInfo<
      '/settings/credentials',
      '/settings/credentials',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/histories': RouteRecordInfo<
      '/settings/histories',
      '/settings/histories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/options': RouteRecordInfo<
      '/settings/options',
      '/settings/options',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ticket/ticket': RouteRecordInfo<
      '/ticket/ticket',
      '/ticket/ticket',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/render/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/render/views/help/help.vue': {
      routes:
        | '/help/help'
      views:
        | never
    }
    'src/render/views/settings/credentials.vue': {
      routes:
        | '/settings/credentials'
      views:
        | never
    }
    'src/render/views/settings/histories.vue': {
      routes:
        | '/settings/histories'
      views:
        | never
    }
    'src/render/views/settings/options.vue': {
      routes:
        | '/settings/options'
      views:
        | never
    }
    'src/render/views/ticket/ticket.vue': {
      routes:
        | '/ticket/ticket'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
